# Odd Ball

# Betting Comparison

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(font_scale=1.5)
%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [8]:
foot_odds = pd.read_csv('csv/football_all.csv')

In [9]:
only_odds = foot_odds.drop(columns=['Div','FTHG', 'FTAG', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'Bb1X2', 'BbOU', 'BbAH', 'BbAHh', 'BbAH', 'BbMxAHH', 
       'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA'])

In [10]:
only_odds.head()

,date,Date,HomeTeam,AwayTeam,FTR,B365H,B365D,B365A,BWH,BWD,...,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
0,2016-08-13,13/08/2016,Burnley,Swansea,A,2.40,3.3,3.25,2.45,3.1,...,3.19,2.50,3.20,2.90,2.50,3.2,3.25,2.79,3.16,2.89
1,2016-08-13,13/08/2016,Crystal Palace,West Brom,A,2.00,3.3,4.50,2.00,3.2,...,4.32,2.05,3.10,4.00,2.00,3.3,4.40,2.25,3.15,3.86
2,2016-08-13,13/08/2016,Everton,Tottenham,D,3.20,3.4,2.40,2.95,3.2,...,2.37,3.10,3.10,2.40,3.25,3.4,2.38,3.64,3.54,2.16
3,2016-08-13,13/08/2016,Hull,Leicester,H,4.50,3.6,1.91,4.33,3.4,...,1.95,4.20,3.25,1.95,4.40,3.5,1.95,4.68,3.50,1.92
4,2016-08-13,13/08/2016,Man City,Sunderland,H,1.25,6.5,15.00,1.22,6.0,...,13.15,1.25,5.50,13.00,1.25,6.5,15.00,1.25,6.50,14.50

In [11]:
only_odds.shape

(1140, 26)

In [12]:
only_odds.columns

Index(['date', 'Date', 'HomeTeam', 'AwayTeam', 'FTR', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [13]:
# convert from decimal to probabilities

here_we_go = ['B365H', 'B365D', 'B365A', 'BWH',
       'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'VCH', 'VCD', 'VCA', 'PSCH', 'PSCD', 'PSCA']

for header in here_we_go:
    only_odds[header] = [1/i for i in only_odds[header]]

In [14]:
only_odds.head()

,date,Date,HomeTeam,AwayTeam,FTR,B365H,B365D,B365A,BWH,BWD,...,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
0,2016-08-13,13/08/2016,Burnley,Swansea,A,0.416667,0.303030,0.307692,0.408163,0.322581,...,0.313480,0.400000,0.312500,0.344828,0.400000,0.312500,0.307692,0.358423,0.316456,0.346021
1,2016-08-13,13/08/2016,Crystal Palace,West Brom,A,0.500000,0.303030,0.222222,0.500000,0.312500,...,0.231481,0.487805,0.322581,0.250000,0.500000,0.303030,0.227273,0.444444,0.317460,0.259067
2,2016-08-13,13/08/2016,Everton,Tottenham,D,0.312500,0.294118,0.416667,0.338983,0.312500,...,0.421941,0.322581,0.322581,0.416667,0.307692,0.294118,0.420168,0.274725,0.282486,0.462963
3,2016-08-13,13/08/2016,Hull,Leicester,H,0.222222,0.277778,0.523560,0.230947,0.294118,...,0.512821,0.238095,0.307692,0.512821,0.227273,0.285714,0.512821,0.213675,0.285714,0.520833
4,2016-08-13,13/08/2016,Man City,Sunderland,H,0.800000,0.153846,0.066667,0.819672,0.166667,...,0.076046,0.800000,0.181818,0.076923,0.800000,0.153846,0.066667,0.800000,0.153846,0.068966

In [15]:
# Converting to numerical values for calculations
only_odds['FTR'] = [0 if i=='H' else 1 if i=='A' else 2 for i in only_odds['FTR']]

In [16]:
only_odds.tail()

,date,Date,HomeTeam,AwayTeam,FTR,B365H,B365D,B365A,BWH,BWD,...,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
1135,2019-05-12,12/05/2019,Liverpool,Wolves,0,0.769231,0.166667,0.090909,0.769231,0.173913,...,0.094877,0.775194,0.181818,0.090909,0.769231,0.173913,0.086957,0.757576,0.169779,0.105485
1136,2019-05-12,12/05/2019,Man United,Cardiff,1,0.781250,0.153846,0.090909,0.800000,0.160000,...,0.097943,0.800000,0.153846,0.100000,0.775194,0.160000,0.090909,0.769231,0.165017,0.102987
1137,2019-05-12,12/05/2019,Southampton,Huddersfield,2,0.694444,0.210526,0.117647,0.704225,0.210526,...,0.131234,0.714286,0.210526,0.125000,0.714286,0.208333,0.117647,0.729927,0.186567,0.117786
1138,2019-05-12,12/05/2019,Tottenham,Everton,2,0.454545,0.285714,0.285714,0.476190,0.285714,...,0.274725,0.476190,0.285714,0.285714,0.476190,0.285714,0.270270,0.523560,0.262467,0.240964
1139,2019-05-12,12/05/2019,Watford,West Ham,1,0.444444,0.266667,0.312500,0.454545,0.270270,...,0.311526,0.454545,0.270270,0.322581,0.454545,0.266667,0.307692,0.473934,0.259067,0.293255

In [17]:

only_odds.drop(columns=['Date'], inplace=True)

In [18]:
# Ensuring uniformaity across dataframes

only_odds['HomeTeam'] = ['ManUtd' if i=='Man United' else i for i in only_odds['HomeTeam']]
only_odds['HomeTeam'] = ['ManCity' if i=='Man City' else i for i in only_odds['HomeTeam']]
only_odds['HomeTeam'] = ['WestHam' if i=='West Ham' else i for i in only_odds['HomeTeam']]
only_odds['HomeTeam'] = ['WestBrom' if i=='West Brom' else i for i in only_odds['HomeTeam']]
only_odds['HomeTeam'] = ['HullCity' if i=='Hull' else i for i in only_odds['HomeTeam']]

In [19]:
only_odds.set_index('date', inplace=True, drop=True)

In [20]:
only_odds['key'] = [str(i)+n[:5] for i,n in zip(only_odds.index, only_odds['HomeTeam'])]

In [226]:
with_probs = pd.read_csv('csv/with_probs_bagcla.csv', index_col=0)

In [227]:
with_probs.columns

Index(['date', 'team1', 'team2', 'score1', 'score2', 'xg1', 'xg2', 'FTR',
       'season_period', 'home_elo', 'away_elo', 'FTR_alpha', 'xg1_5g_avg',
       'xg2_5g_avg', 'gd_5g_avg', 'game1', 'game2', 'game3', 'game4', 'game5',
       'HomeWin', 'AwayWin', 'Draw'],
      dtype='object')

In [263]:
# Only taking the columns we need, that is, the predicted outcomes
only_probs = with_probs[['date', 'team1', 'team2','HomeWin', 'Draw', 'AwayWin', 'FTR']]

In [264]:
only_probs.head(10)

         date    team1              team2  HomeWin   Draw  AwayWin  FTR
0  2016-10-22  Burnley            Everton    0.190  0.199    0.611    0
1  2016-11-05  Burnley     Crystal Palace    0.550  0.223    0.226    0
2  2016-11-26  Burnley            ManCity    0.636  0.136    0.228    1
3  2016-12-10  Burnley        Bournemouth    0.610  0.083    0.306    0
4  2016-12-26  Burnley      Middlesbrough    0.593  0.205    0.202    0
5  2016-12-31  Burnley         Sunderland    0.285  0.250    0.465    0
6  2017-01-14  Burnley        Southampton    0.645  0.243    0.111    0
7  2017-01-31  Burnley     Leicester City    0.314  0.092    0.594    0
8  2017-02-12  Burnley            Chelsea    0.527  0.313    0.160    2
9  2017-04-01  Burnley  Tottenham Hotspur    0.305  0.167    0.528    1

In [265]:
only_probs.set_index('date', inplace=True, drop=True)

In [266]:
only_probs['key'] = [str(i)+n[:5] for i,n in zip(only_probs.index, only_probs['team1'])]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [267]:
only_probs.head()

,team1,team2,HomeWin,Draw,AwayWin,FTR,key
date,,,,,,,
2016-10-22,Burnley,Everton,0.190,0.199,0.611,0,2016-10-22Burnl
2016-11-05,Burnley,Crystal Palace,0.550,0.223,0.226,0,2016-11-05Burnl
2016-11-26,Burnley,ManCity,0.636,0.136,0.228,1,2016-11-26Burnl
2016-12-10,Burnley,Bournemouth,0.610,0.083,0.306,0,2016-12-10Burnl
2016-12-26,Burnley,Middlesbrough,0.593,0.205,0.202,0,2016-12-26Burnl

In [268]:
only_odds.head()

,HomeTeam,AwayTeam,FTR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA,key
date,,,,,,,,,,,,,,,,,,,,,,,,,
2016-08-13,Burnley,Swansea,1,0.416667,0.303030,0.307692,0.408163,0.322581,0.338983,0.400000,0.303030,0.377358,0.404858,0.301205,0.313480,0.400000,0.312500,0.344828,0.400000,0.312500,0.307692,0.358423,0.316456,0.346021,2016-08-13Burnl
2016-08-13,Crystal Palace,West Brom,1,0.500000,0.303030,0.222222,0.500000,0.312500,0.256410,0.476190,0.303030,0.303030,0.485437,0.303951,0.231481,0.487805,0.322581,0.250000,0.500000,0.303030,0.227273,0.444444,0.317460,0.259067,2016-08-13Cryst
2016-08-13,Everton,Tottenham,2,0.312500,0.294118,0.416667,0.338983,0.312500,0.416667,0.377358,0.303030,0.400000,0.307692,0.291545,0.421941,0.322581,0.322581,0.416667,0.307692,0.294118,0.420168,0.274725,0.282486,0.462963,2016-08-13Evert
2016-08-13,HullCity,Leicester,0,0.222222,0.277778,0.523560,0.230947,0.294118,0.526316,0.303030,0.303030,0.476190,0.225734,0.281690,0.512821,0.238095,0.307692,0.512821,0.227273,0.285714,0.512821,0.213675,0.285714,0.520833,2016-08-13HullC
2016-08-13,ManCity,Sunderland,0,0.800000,0.153846,0.066667,0.819672,0.166667,0.086957,0.800000,0.181818,0.097087,0.787402,0.154321,0.076046,0.800000,0.181818,0.076923,0.800000,0.153846,0.066667,0.800000,0.153846,0.068966,2016-08-13ManCi

In [269]:
only_odds.sort_values('key', inplace=True)

In [270]:
only_probs.sort_values('key', inplace=True)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [271]:
only_odds.head()

,HomeTeam,AwayTeam,FTR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA,key
date,,,,,,,,,,,,,,,,,,,,,,,,,
2016-08-13,Burnley,Swansea,1,0.416667,0.303030,0.307692,0.408163,0.322581,0.338983,0.400000,0.303030,0.377358,0.404858,0.301205,0.313480,0.400000,0.312500,0.344828,0.400000,0.312500,0.307692,0.358423,0.316456,0.346021,2016-08-13Burnl
2016-08-13,Crystal Palace,West Brom,1,0.500000,0.303030,0.222222,0.500000,0.312500,0.256410,0.476190,0.303030,0.303030,0.485437,0.303951,0.231481,0.487805,0.322581,0.250000,0.500000,0.303030,0.227273,0.444444,0.317460,0.259067,2016-08-13Cryst
2016-08-13,Everton,Tottenham,2,0.312500,0.294118,0.416667,0.338983,0.312500,0.416667,0.377358,0.303030,0.400000,0.307692,0.291545,0.421941,0.322581,0.322581,0.416667,0.307692,0.294118,0.420168,0.274725,0.282486,0.462963,2016-08-13Evert
2016-08-13,HullCity,Leicester,0,0.222222,0.277778,0.523560,0.230947,0.294118,0.526316,0.303030,0.303030,0.476190,0.225734,0.281690,0.512821,0.238095,0.307692,0.512821,0.227273,0.285714,0.512821,0.213675,0.285714,0.520833,2016-08-13HullC
2016-08-13,ManCity,Sunderland,0,0.800000,0.153846,0.066667,0.819672,0.166667,0.086957,0.800000,0.181818,0.097087,0.787402,0.154321,0.076046,0.800000,0.181818,0.076923,0.800000,0.153846,0.066667,0.800000,0.153846,0.068966,2016-08-13ManCi

In [272]:
only_probs.head()

,team1,team2,HomeWin,Draw,AwayWin,FTR,key
date,,,,,,,
2016-10-22,Burnley,Everton,0.190,0.199,0.611,0,2016-10-22Burnl
2016-11-05,Bournemouth,Sunderland,0.330,0.255,0.415,1,2016-11-05Bourn
2016-11-05,Burnley,Crystal Palace,0.550,0.223,0.226,0,2016-11-05Burnl
2016-11-05,Chelsea,Everton,0.427,0.064,0.509,0,2016-11-05Chels
2016-11-05,ManCity,Middlesbrough,0.644,0.142,0.214,2,2016-11-05ManCi

In [273]:
only_odds.shape, only_probs.shape

((1140, 25), (1010, 7))

In [274]:
# Sort out the discrepancies in the shape by merging on the smaller dataset
odds_probs = pd.merge(left=only_probs, right=only_odds, left_on='key', right_on='key', how='left')

In [276]:
odds_probs.shape

(1010, 31)

In [277]:
# Smashing

In [279]:
odds_probs.head()

,team1,team2,HomeWin,Draw,AwayWin,FTR_x,key,HomeTeam,AwayTeam,FTR_y,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
0,Burnley,Everton,0.190,0.199,0.611,0,2016-10-22Burnl,Burnley,Everton,0,0.166667,0.263158,0.598802,0.166667,0.263158,0.617284,0.208333,0.277778,0.571429,0.165289,0.258398,0.595238,0.166667,0.277778,0.598802,0.160000,0.263158,0.598802,0.169492,0.268097,0.584795
1,Bournemouth,Sunderland,0.330,0.255,0.415,1,2016-11-05Bourn,Bournemouth,Sunderland,1,0.606061,0.238095,0.181818,0.617284,0.256410,0.173913,0.606061,0.263158,0.188679,0.613497,0.234192,0.173010,0.598802,0.277778,0.166667,0.606061,0.250000,0.173913,0.613497,0.227273,0.178253
2,Burnley,Crystal Palace,0.550,0.223,0.226,0,2016-11-05Burnl,Burnley,Crystal Palace,0,0.303030,0.303030,0.420168,0.312500,0.307692,0.425532,0.338983,0.303030,0.416667,0.292398,0.296736,0.431034,0.303030,0.322581,0.416667,0.285714,0.303030,0.434783,0.277778,0.305810,0.436681
3,Chelsea,Everton,0.427,0.064,0.509,0,2016-11-05Chels,Chelsea,Everton,0,0.653595,0.230947,0.142857,0.653595,0.238095,0.160000,0.645161,0.250000,0.161290,0.636943,0.228833,0.154560,0.636943,0.266667,0.142857,0.636943,0.230947,0.153846,0.666667,0.216920,0.135135
4,ManCity,Middlesbrough,0.644,0.142,0.214,2,2016-11-05ManCi,ManCity,Middlesbrough,2,0.819672,0.142857,0.066667,0.833333,0.148148,0.068966,0.833333,0.153846,0.066667,0.813008,0.139665,0.070323,0.819672,0.153846,0.076923,0.819672,0.142857,0.066667,0.819672,0.132450,0.067797

In [280]:
odds_probs.columns

Index(['team1', 'team2', 'HomeWin', 'Draw', 'AwayWin', 'FTR_x', 'key',
       'HomeTeam', 'AwayTeam', 'FTR_y', 'B365H', 'B365D', 'B365A', 'BWH',
       'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'VCH', 'VCD', 'VCA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [281]:
odds_probs['FTR'] = odds_probs['FTR_x']

In [282]:
odds_probs.drop(columns=['key', 'HomeTeam', 'AwayTeam', 'FTR_y', 'FTR_x'], inplace=True)

In [283]:
odds_probs.head()

,team1,team2,HomeWin,Draw,AwayWin,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA,FTR
0,Burnley,Everton,0.190,0.199,0.611,0.166667,0.263158,0.598802,0.166667,0.263158,0.617284,0.208333,0.277778,0.571429,0.165289,0.258398,0.595238,0.166667,0.277778,0.598802,0.160000,0.263158,0.598802,0.169492,0.268097,0.584795,0
1,Bournemouth,Sunderland,0.330,0.255,0.415,0.606061,0.238095,0.181818,0.617284,0.256410,0.173913,0.606061,0.263158,0.188679,0.613497,0.234192,0.173010,0.598802,0.277778,0.166667,0.606061,0.250000,0.173913,0.613497,0.227273,0.178253,1
2,Burnley,Crystal Palace,0.550,0.223,0.226,0.303030,0.303030,0.420168,0.312500,0.307692,0.425532,0.338983,0.303030,0.416667,0.292398,0.296736,0.431034,0.303030,0.322581,0.416667,0.285714,0.303030,0.434783,0.277778,0.305810,0.436681,0
3,Chelsea,Everton,0.427,0.064,0.509,0.653595,0.230947,0.142857,0.653595,0.238095,0.160000,0.645161,0.250000,0.161290,0.636943,0.228833,0.154560,0.636943,0.266667,0.142857,0.636943,0.230947,0.153846,0.666667,0.216920,0.135135,0
4,ManCity,Middlesbrough,0.644,0.142,0.214,0.819672,0.142857,0.066667,0.833333,0.148148,0.068966,0.833333,0.153846,0.066667,0.813008,0.139665,0.070323,0.819672,0.153846,0.076923,0.819672,0.142857,0.066667,0.819672,0.132450,0.067797,2

In [284]:
odds_probs.to_csv('csv/odds_probs_clean.csv')

In [285]:
odds_probs = pd.read_csv('csv/odds_probs_clean.csv', index_col=0)

In [286]:
cols = odds_probs.columns[2:-1]

In [287]:
cols

Index(['HomeWin', 'Draw', 'AwayWin', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA',
       'VCH', 'VCD', 'VCA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [288]:
df_odds_probs_clean = odds_probs.copy()

In [289]:
df_odds_probs_clean.columns

Index(['team1', 'team2', 'HomeWin', 'Draw', 'AwayWin', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'PSCH', 'PSCD', 'PSCA',
       'FTR'],
      dtype='object')

In [290]:
df_odds_probs_clean = df_odds_probs_clean[['team1', 'team2', 'HomeWin', 'Draw', 'AwayWin', 'FTR', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'PSCH', 'PSCD', 'PSCA']]

In [291]:
# Using Bagging Classifier - first value is the accuracy across three seaons for my model, the other numbers
# are the accuracy for the various bookmakers across the same time period

for col in range(0,24,3):
    checkywecky = []
    for i in range(len(df_odds_probs_clean)):
        checkywecky.append(np.argmax(df_odds_probs_clean[[cols[col], cols[col+1], cols[col+2]]].iloc[i]))
        
    print(sum([1 if j==n else 0 for j,n in 
     zip([0 if i==cols[col] else 1 if i==cols[col+2] else 2 for i in checkywecky], 
         df_odds_probs_clean['FTR'])])/1010)

0.4188118811881188
0.5851485148514851
0.5841584158415841
0.5881188118811881
0.5831683168316831
0.5861386138613861
0.5841584158415841
0.5811881188118811

In [258]:
for col in range(0,24,3):
    
    list_lists = []
    for index, row in odds_probs.iterrows():
        list_lists.append(list((row[cols[col]], row[cols[col+1]], row[cols[col+2]])))
    
    the_best = []
    positions = []
    
    for pos in list_lists:
        
        the_best.append(max(pos))
        
        if np.argmax(pos) == 0:
            positions.append(0)
            
        elif np.argmax(pos) == 1:
            positions.append(2)
            
        else:
            positions.append(1)
    
    print(set(positions))
    accurate_guesses = []
    for pred, actual in zip(df_odds_probs_clean['FTR'], positions):
        if pred == actual:
            accurate_guesses.append(1)
        else:
            accurate_guesses.append(0)

    df_odds_probs_clean[str(cols[col][:-1]) + '_best'] = the_best
    df_odds_probs_clean[str(cols[col][:-1]) + '_pred'] = accurate_guesses

{0, 1, 2}
{0, 1}
{0, 1}
{0, 1}
{0, 1}
{0, 1}
{0, 1}
{0, 1}

In [292]:
# by printing set(positions) we can see that over the course of 3 seasons the bookies never favoured a draw...
# This could be interesting...

In [293]:
pd.options.display.max_columns = 100

In [294]:
df_odds_probs_clean.head(10)

,team1,team2,HomeWin,Draw,AwayWin,FTR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
0,Burnley,Everton,0.190,0.199,0.611,0,0.166667,0.263158,0.598802,0.166667,0.263158,0.617284,0.208333,0.277778,0.571429,0.165289,0.258398,0.595238,0.166667,0.277778,0.598802,0.160000,0.263158,0.598802,0.169492,0.268097,0.584795
1,Bournemouth,Sunderland,0.330,0.255,0.415,1,0.606061,0.238095,0.181818,0.617284,0.256410,0.173913,0.606061,0.263158,0.188679,0.613497,0.234192,0.173010,0.598802,0.277778,0.166667,0.606061,0.250000,0.173913,0.613497,0.227273,0.178253
2,Burnley,Crystal Palace,0.550,0.223,0.226,0,0.303030,0.303030,0.420168,0.312500,0.307692,0.425532,0.338983,0.303030,0.416667,0.292398,0.296736,0.431034,0.303030,0.322581,0.416667,0.285714,0.303030,0.434783,0.277778,0.305810,0.436681
3,Chelsea,Everton,0.427,0.064,0.509,0,0.653595,0.230947,0.142857,0.653595,0.238095,0.160000,0.645161,0.250000,0.161290,0.636943,0.228833,0.154560,0.636943,0.266667,0.142857,0.636943,0.230947,0.153846,0.666667,0.216920,0.135135
4,ManCity,Middlesbrough,0.644,0.142,0.214,2,0.819672,0.142857,0.066667,0.833333,0.148148,0.068966,0.833333,0.153846,0.066667,0.813008,0.139665,0.070323,0.819672,0.153846,0.076923,0.819672,0.142857,0.066667,0.819672,0.132450,0.067797
5,WestHam,Stoke City,0.284,0.091,0.625,2,0.500000,0.277778,0.250000,0.500000,0.285714,0.263158,0.500000,0.294118,0.263158,0.500000,0.278552,0.242131,0.487805,0.303030,0.250000,0.487805,0.277778,0.256410,0.497512,0.283286,0.239808
6,Arsenal,Tottenham Hotspur,0.742,0.110,0.148,2,0.512821,0.277778,0.238095,0.512821,0.277778,0.256410,0.500000,0.294118,0.263158,0.512821,0.278552,0.229885,0.500000,0.312500,0.230947,0.512821,0.285714,0.238095,0.507614,0.275482,0.238095
7,HullCity,Southampton,0.564,0.062,0.374,0,0.173913,0.263158,0.588235,0.181818,0.263158,0.606061,0.188679,0.263158,0.606061,0.174520,0.257732,0.588235,0.181818,0.277778,0.588235,0.173913,0.266667,0.588235,0.173913,0.256410,0.591716
8,Leicester City,WestBrom,0.220,0.248,0.532,1,0.555556,0.277778,0.190476,0.561798,0.277778,0.210526,0.571429,0.277778,0.208333,0.561798,0.275482,0.182149,0.555556,0.303030,0.181818,0.555556,0.277778,0.192308,0.574713,0.268817,0.176991
9,Swansea City,ManUtd,0.334,0.204,0.462,1,0.200000,0.250000,0.578035,0.210526,0.256410,0.581395,0.188679,0.263158,0.606061,0.202429,0.249377,0.568182,0.200000,0.266667,0.578035,0.200000,0.250000,0.578035,0.180832,0.247525,0.591716